# Makefile - Wolfson Microelectronics 8962 Audio Codec Driver src Makefile
#
# Copyright (c) 2014, 2021 Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
OBJS = audioDrvWm8962.o
LIB_BASE_NAME = audioDrvWm8962

include $(WIND_KRNL_MK)/rules.library.mk