# Makefile - Freescale SSI Audio Driver src Makefile
#
# Copyright (c) 2014, 2021 Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
OBJS = audioDrvFslSsi.o
LIB_BASE_NAME = audioDrvFslSsi

include $(WIND_KRNL_MK)/rules.library.mk